### ISSUE TITLE
Bump replaces dependency versions as well

### ISSUE THREAD

**Issue by cubytz** [mpanarin/versioce#21]
Thank you for the great project! I love it! I started using it and I just notice the following scenario:

Let's say you have a `mix.exs` file like this:

``` elixir
def project do
    [
      app: :my_app,
      version: 0.3.0,
      ...
    ]
end

...

defp deps do
    [
      {:git_cli, "~> 0.3.0", optional: true}
    ]
end
```

Running `mix bump 0.1.0` will set `{:git_cli, "~> 0.1.0", optional: true}` (Or would increase the version if the pattern matches). This is dangerous as could lead to versions that can break the code (`Because "versioce >= 1.0.0" depends on "git_cli ~> 0.3.0" and "your app" depends on "git_cli ~> 0.1.0", "versioce >= 1.0.0" is forbidden.`).

I'm wondering if we could either make sure we change just the version and not the dependencies or we allow an exclude option in the config, like this:

``` elixir
config :versioce,
  files: [
    "README.md",
    "VERSION"
  ],
  exclude_files: [
    "mix.exs",
    ...
  ],
  post_hooks: [
    ...
  ]
```

Would love to hear your thoughts and make a PR. Thank you!

**Comment by mpanarin** [comment]
Thanks for the kind words.

This behavior is configured via `global` value (https://hexdocs.pm/versioce/Versioce.Config.html#global/0)
It should be `false` by default. Are you sure you don't have this value set?

**Comment by cubytz** [comment]
I actually was using a VERSION file that contained the version number. `mix.exs` was reading the VERSION file, so `mix bump` actually updated the first corresponding number it found. My bad! Thank you for your help! I'll close this issue.

**Comment by mpanarin** [comment]
This can be a common issue, actually. Maybe I should remove mix.exs from files to update by default. And make sure that only files specified in `files` are updated.

I'll make a note for myself for a next major release.
